name: Publish 🚀

on:
  workflow_dispatch:
  push:
    branches: 
      - main

env:
  AZURE_WEBAPP_NAME: transtopSystems

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Deployment
        uses: actions/webapps-deploy@v2
        with: 
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ''
          package: '.'
