name: Publish 🚀

on:
  workflow_dispatch:
  push:
    branches: 
    - main

env:
  AZURE_WEBAPP_NAME: transtopSystems
  AZURE_WEBAPP_PACKAGE_PATH: "./publish"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Deployment
      uses: azure/webapps-deploy@v2
      with: 
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        package: .
